filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/docker/volumes/travelplanner_spring-boot-logs/_data/roamgram.log
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  - type: tcp
    enabled: true
    host: "0.0.0.0:5044"
    max_message_size: 10MiB
    ssl:
      enabled: false
      # Uncomment and set the certificate and key paths if using SSL
      # certificate: "/path/to/cert.pem"
      # key: "/path/to/key.pem"

output.logstash:
  hosts: ["172.17.0.1:5044"]

#output.console:

