#-------------------------------- Autodiscovery -------------------------------
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.modules:
  #------------------------------- System Module -------------------------------
  - module: system
    metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    period: 10s
    cpu.metrics:  ["percentages"]
    core.metrics: ["percentages"]

  - module: system
    period: 1m
    metricsets:
      - filesystem
      - fsstat
    processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

  - module: system
    period: 15m
    metricsets:
      - uptime

  - module: http
    period: 60s
    hosts: [ "https://spring-boot-app:443" ]
    path: "/actuator/metrics"
    ssl.verification_mode: none  # Change to 'full' if you are using a valid certificate
    # ssl.certificate_authorities: ["path/to/ca.crt"]  # Uncomment if using custom CA
    # ssl.certificate: "path/to/client.crt"  # Uncomment if client certificates are required
    # ssl.key: "path/to/client.key"  # Uncomment if client certificates are required
    namespace: "springboot.actuator"
    data_stream:
      namespace: default
    metricsets: [ "json" ]  # Adding the required metricset

  #------------------------------- Docker Module -------------------------------
  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

#================================ Processors ===================================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true


output.logstash:
  hosts: [ "172.17.0.1:5044" ]  # Use the IP address or hostname of the Logstash server