spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILSENDER_EMAIL}
    password: ${EMAILSENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required=true:
    default-encoding: UTF-8
    protocol: smtp
  application:
    name: travelDiaryTest

  jpa:
    hibernate:
      ddl-auto: create-drop  # Create and drop the database schema for each test run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Use H2 in-memory database for tests

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6380  # You can keep this as is if you are running Redis locally for tests

frontend:
  uri: https://roamgram-deployment.vercel.app/

devserver:
  uri: https://3.24.135.223:443