spring:
  application:
    name: travelDiary

#    uncomment below before doing local dev work.
  profiles:
    include: secretsLocal

#    uncomment below before using buildx or GitHub workflow
#  profiles:
#    active: prod
#    include: prodsecrets
