spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILSENDER_EMAIL}
    password: ${EMAILSENDER_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          connectiontimeout: 10000
          auth: true
          starttls:
            enable: true
            required=true:
    default-encoding: UTF-8
    protocol: smtp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

frontend:
  uri: ${FRONTEND_URL}
