aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    profile:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
  ec2:
    uri: ${AWS_EC2_URI}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILSENDER_EMAIL}
    password: ${EMAILSENDER_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          connectiontimeout: 10000
          auth: true
          starttls:
            enable: true
            required=true:
    default-encoding: UTF-8
    protocol: smtp

  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-id: ${GOOGLE_CLIENT_ID}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

jjwt:
  key: ${JWT_KEY}

server:
  port: 443
  ssl:
    key-store: ./keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: roamgram
    enabled: true

devserver:
  uri: https://3.24.135.223:443