spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/roamgram

  # Remove H2-specific settings
  # If you don't need the H2 console anymore, you can omit this section

  # spring:
  #   h2:
  #     console:
  #       enabled: true
  #       path: /h2-console

  data:
    redis:
      host: redis
      port: 6379
