spring:
  application:
    name: travelDiaryTest

  jpa:
    hibernate:
      ddl-auto: create-drop  # Create and drop the database schema for each test run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Use H2 in-memory database for tests

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:./roamGram;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6380  # You can keep this as is if you are running Redis locally for tests
