spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: roamgram.noreply@gmail.com
    password: NUS1004^^
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    protocol: smtp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect

# for local development my macOS postgres server will be used to run
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/roamgram

  data:
    redis:
      host: localhost
      port: 6380




frontend:
  uri: https://roamgram-deployment.vercel.app/

