spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect

# for local development my macOS postgres server will be used to run
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/roamgram

  data:
    redis:
      host: localhost
      port: 6380

frontend:
  uri: https://roamgram-deployment.vercel.app/

