spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:./roamGram;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;

  h2:
    console:
      enabled: true
      path: /h2-console
