version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: elasticsearch
    platform: linux/arm64
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Optional: Disable security for testing purposes
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      my-network:
        aliases:
          - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.2
    container_name: logstash
    platform: linux/arm64
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - my-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.2
    container_name: kibana
    platform: linux/arm64
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - my-network

volumes:
  esdata:
    driver: local

networks:
  my-network:
    driver: bridge
