name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_STORE_BASE64: ${{ secrets.KEY_STORE_BASE64 }}

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode and store keystore
        run: echo $KEY_STORE_BASE64 | base64 --decode > keystore.p12

      - name: Set up environment variables
        run: |
          echo "AWS_S3_ACCESS_KEY=${{ secrets.AMAZON_S3_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_S3_SECRET_KEY=${{ secrets.AMAZON_S3_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=${{ secrets.AMAZON_S3_BUCKET }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AMAZON_S3_REGION_STATIC }}" >> $GITHUB_ENV
          echo "AWS_EC2_URI=${{ secrets.AMAZON_EC2_URI }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JJWT_KEY }}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> $GITHUB_ENV
          echo "REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "REDIS_PORT=6379" >> $GITHUB_ENV
          echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> $GITHUB_ENV
          echo "EMAILSENDER_EMAIL=${{ secrets.EMAILSENDER_EMAIL }}" >> $GITHUB_ENV
          echo "EMAILSENDER_PASSWORD=${{ secrets.EMAILSENDER_PASSWORD }}" >> $GITHUB_ENV
        shell: bash

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/roamgram:latest
          build-args: |
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            AWS_S3_ACCESS_KEY=${{ secrets.AMAZON_S3_ACCESS_KEY }}
            AWS_S3_SECRET_KEY=${{ secrets.AMAZON_S3_SECRET_KEY }}
            AWS_S3_BUCKET=${{ secrets.AMAZON_S3_BUCKET }}
            AWS_REGION=${{ secrets.AMAZON_S3_REGION_STATIC }}
            AWS_EC2_URI=${{ secrets.AMAZON_EC2_URI }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            JWT_KEY=${{ secrets.JJWT_KEY }}
            KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            EMAILSENDER_EMAIL=${{ secrets.EMAILSENDER_EMAIL }}
            EMAILSENDER_PASSWORD=${{ secrets.EMAILSENDER_PASSWORD }}

      - name: Run Docker container to get jacoco report.
        run: docker run --name myapp-container -d ${{ secrets.DOCKER_USERNAME }}/roamgram:latest

      - name: Copy JaCoCo XML Report from Docker container
        run: docker cp myapp-container:/app/build/reports/jacoco/test/jacocoTestReport.xml ./jacocoTestReport.xml

      - name: Stop and remove Docker container
        run: |
          docker stop myapp-container
          docker rm myapp-container

      - name: Create JaCoCo report directory
        run: mkdir -p jacoco-report

      - name: Move JaCoCo report to directory
        run: |
          mv jacocoTestReport.xml jacoco-report/


      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-xml-report
          path: jacoco-report/jacocoTestReport.xml
