name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use --bootstrap
          docker buildx inspect --bootstrap

      - name: Set environment variables for Docker Compose
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env

      - name: Build and Push Docker image
        run: |
          docker buildx bake -f docker-compose-bake.yml